In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import matplotlib

In [3]:
df = pd.read_csv('C:\\Users\\aviji\\Desktop\\capstone_project_1\\olist_customers_dataset.csv')
df.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB

In [5]:
df.isnull().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [6]:
df.describe()

       customer_zip_code_prefix
count              99441.000000
mean               35137.474181
std                29797.939288
min                 1003.000000
25%                11347.000000
50%                24416.000000
75%                58900.000000
max                99990.000000

In [7]:
df.rename(columns={"customer_zip_code_prefix" :"customer_zip_code"}, inplace=True)

In [8]:
df.columns

Index(['customer_id', 'customer_unique_id', 'customer_zip_code',
       'customer_city', 'customer_state'],
      dtype='object')

In [9]:
col = "customer_city"                      # <-- yaha apna column naam daal

df[col] = df[col].str.lower().str.strip()  # lowercase + trim spaces
df[col] = df[col].str.replace(r"\s+", " ", regex=True)  # extra spaces hataye

print(df[col].unique())                    # clean values check
df.to_csv("cleaned.csv", index=False)

['franca' 'sao bernardo do campo' 'sao paulo' ... 'monte bonito'
 'sao rafael' 'eugenio de castro']

In [10]:
print("Duplicate rows:", df.duplicated().sum())

# show duplicate rows
dup_rows = df[df.duplicated()]
print(dup_rows.head())

# remove duplicates
df = df.drop_duplicates()

Duplicate rows: 0
Empty DataFrame
Columns: [customer_id, customer_unique_id, customer_zip_code, customer_city, customer_state]
Index: []

In [11]:
df.columns

Index(['customer_id', 'customer_unique_id', 'customer_zip_code',
       'customer_city', 'customer_state'],
      dtype='object')

In [12]:
col = "customer_unique_id"

print("Duplicate count:", df.duplicated(subset=[col]).sum())

# rows where column is duplicated
dup_col = df[df.duplicated(subset=[col], keep=False)]
print(dup_col.head())

Duplicate count: 3345
                         customer_id                customer_unique_id  \
5   879864dab9bc3047522c92c82e1212b8  4c93744516667ad3b8f1fb645a3116a4
8   5adf08e34b2e993982a47070956c5c65  1175e95fb47ddff9de6b2b06188f7e0d
13  eabebad39a88bb6f5b52376faec28612  295c05e81917928d76245e842748184d
32  2d5831cb2dff7cdefba62e950ae3dc7b  e9dd12dca17352644a959d9dea133935
33  b2bed119388167a954382cca36c4777f  e079b18794454de9d2be5c12b4392294

    customer_zip_code   customer_city customer_state
5               89254  jaragua do sul             SC
8               81560        curitiba             PR
13               5704       sao paulo             SP
32              42800        camacari             BA
33              27525         resende             RJ

In [13]:
for c in df.columns:
    if df[c].duplicated().sum() > 0:
        print(c, "→", df[c].duplicated().sum(), "duplicates")

customer_unique_id → 3345 duplicates
customer_zip_code → 84446 duplicates
customer_city → 95322 duplicates
customer_state → 99414 duplicates

In [14]:
cols_to_string = ["customer_city", "customer_state"]  
# ↑ yaha apne column naam daal do (jitne chaho)

for c in cols_to_string:
    df[c] = df[c].astype(str).str.strip()
    
display(df)

,customer_id,customer_unique_id,customer_zip_code,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP
...,...,...,...,...,...
99436,17ddf5dd5d51696bb3d7c6291687be6f,1a29b476fee25c95fbafc67c5ac95cf8,3937,sao paulo,SP
99437,e7b71a9017aa05c9a7fd292d714858e8,d52a67c98be1cf6a5c84435bd38d095d,6764,taboao da serra,SP
99438,5e28dfe12db7fb50a4b2f691faecea5e,e9f50caf99f032f0bf3c55141f019d99,60115,fortaleza,CE
99439,56b18e2166679b8a959d72dd06da27f9,73c2643a0a458b49f58cea58833b192e,92120,canoas,RS
99440,274fa6071e5e17fe303b9748641082c8,84732c5050c01db9b23e19ba39899398,6703,cotia,SP

In [15]:
display(df)

,customer_id,customer_unique_id,customer_zip_code,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP
...,...,...,...,...,...
99436,17ddf5dd5d51696bb3d7c6291687be6f,1a29b476fee25c95fbafc67c5ac95cf8,3937,sao paulo,SP
99437,e7b71a9017aa05c9a7fd292d714858e8,d52a67c98be1cf6a5c84435bd38d095d,6764,taboao da serra,SP
99438,5e28dfe12db7fb50a4b2f691faecea5e,e9f50caf99f032f0bf3c55141f019d99,60115,fortaleza,CE
99439,56b18e2166679b8a959d72dd06da27f9,73c2643a0a458b49f58cea58833b192e,92120,canoas,RS
99440,274fa6071e5e17fe303b9748641082c8,84732c5050c01db9b23e19ba39899398,6703,cotia,SP

In [16]:
df.to_csv("cleaned_cust.csv", index=False)

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   customer_id         99441 non-null  object
 1   customer_unique_id  99441 non-null  object
 2   customer_zip_code   99441 non-null  int64
 3   customer_city       99441 non-null  object
 4   customer_state      99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB